### ISSUE TITLE
Any idea about audio source as local microphone input

### ISSUE THREAD

**Issue by rtgiskard** [agarciadom/ipwebcam-gst#125]
Thanks a lot for the works, I have just write another [ipWebcam_cli](https://github.com/rtgiskard/ipWebcam_cli) with python.

I'd like to use the audio source from android as the local microphone input, but not read it well for the `pactl` part. Here find a related [discussion](https://stackoverflow.com/questions/43480867/linux-pipe-audio-file-to-microphone-input), but I'm not ready to try at the time (maybe later 😵).

If you have any more guide, I'll appreciate a lot 😃

**Comment by rtgiskard** [comment]
Resolved by the reference:

. https://superuser.com/a/1687100
. https://luke.hsiao.dev/blog/pipewire-virtual-microphone/

**Comment by Urbaner3** [comment]
I open an PR with item #129 maybe you may check if your audio controler is pipewire-alse or pulseaudio, which the latter is preferred in the functioning of this software.
Can you show me the file in your fork please, so I would see another way around?
