### ISSUE TITLE
Stream ended unexpectedly!

### ISSUE THREAD

**Issue by WaflanCZ** [agarciadom/ipwebcam-gst#127]
I can connect to my phone but imidietly after that it crashes and says this: Stream ended unexpectedly!

**Comment by Zeal5** [comment]
Same warning here!
tried connecting both ways wireless and with cable

**Comment by adasium** [comment]
in my case I had a `feed.log`  file  with contents `Error initializing: Unknown option --gst-plugin-spew`
removing this option worked

**Comment by bermudi** [comment]
Same here, tried with Xiaomi and Huawei phones and both end unexpectedly right after starting

**Comment by acora192** [comment]
So I finally found the issue. I asked chatgpt and the thing is that there was an update over gstreamer and the syntax changed. So you only a line must be changed on the run script:

```bash
JOB_NAME='stream' JOB_LOG=feed.log JOB_INTRO_CMD=stream_intro JOB_FAILURE_CMD=stream_failure \
    monitor_job "$GSTLAUNCH" -e -vt --gst-debug --gst-debug="$GST_DEBUG" $PIPELINE
    # Maybe we need edit this pipeline to transfer it to "Monitor of IP Webcam" to be able to use it as a microphone?
```
Change ```--gst-plugin-spew``` to ```--gst-debug``` on line 643 of run-videochat.sh

**Comment by agarciadom** [comment]
Thank you for proposing a fix! I think `--gst-debug` by itself doesn't do much: I just dropped `--gst-plugin-spew` as that is no longer listed in the `gst-launch` manpage:

https://gstreamer.freedesktop.org/documentation/tools/gst-launch.html
